### ISSUE TITLE
Is this lib deprecated?

### ISSUE THREAD

**Issue by ssordatic** [ahmadnassri/node-har-validator#173]
Hello I'm getting this error in npm when I install loopback
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

**Comment by erunion** [comment]
Also curious the background on this. If you need a new maintainer, we're willing to take it on at @readmeio.

**Comment by ahmadnassri** [comment]
indeed, i'm no longer able to maintain this library.

complications include:

- being nested in dep chain of many projects due to `request` lib using it _(my fault)_
- npm cli itself is dependant on this (because of `request`) which also means the entirety of Node.js is dependant on this library not breaking...

if you're wiling to take ownership of it, I can happily pass it, but be warned, and do your research first (see issues for history of pain) to see what you're adopting.

**Comment by ahmadnassri** [comment]
that said, this is technically feature complete, and aside from dependency updates (because security warnings) there is not much to improve / add / change in the functionality ...

**Comment by ktalebian** [comment]
@ahmadnassri since this is now marked as no longer supported, it always logs

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

Whenever you are using a package that depends on this. Can we either transfer the ownership or undo the npm warning?

**Comment by ahmadnassri** [comment]
I think the deprecation and the warning are functionning as expected, if you don't want to see warnings, set the npm [`loglevel` to `error`](https://docs.npmjs.com/cli/v6/using-npm/config#loglevel)
